
// This file is auto-generated by @chainsafe/bun-ffi-z. Do not edit.

import path from "node:path";
import { openLibrary } from "@chainsafe/bun-ffi-z";

const fns = {
  "u64_to_bytes": {
    "args": [
      "u64",
      "ptr",
      "u32",
      "bool"
    ],
    "returns": "i32"
  },
  "bytes_to_u64": {
    "args": [
      "ptr",
      "u32",
      "bool"
    ],
    "returns": "u64"
  },
  "bytes_to_u64_fast": {
    "args": [
      "ptr",
      "u32",
      "bool"
    ],
    "returns": "ptr"
  },
  "hashtree_hash_": {
    "args": [
      "ptr",
      "ptr",
      "u64"
    ],
    "returns": "i32"
  },
  "err_name": {
    "args": [
      "u16"
    ],
    "returns": "cstring"
  },
  "persistent_merkle_tree_pool_init": {
    "args": [
      "u32"
    ],
    "returns": "i32"
  },
  "persistent_merkle_tree_pool_deinit": {
    "args": [],
    "returns": "void"
  },
  "persistent_merkle_tree_pool_create_leaf": {
    "args": [
      "ptr",
      "bool"
    ],
    "returns": "i32"
  },
  "persistent_merkle_tree_pool_create_branch": {
    "args": [
      "u32",
      "u32",
      "bool"
    ],
    "returns": "i32"
  },
  "persistent_merkle_tree_pool_ref": {
    "args": [
      "u32"
    ],
    "returns": "i32"
  },
  "persistent_merkle_tree_pool_unref": {
    "args": [
      "u32"
    ],
    "returns": "void"
  },
  "persistent_merkle_tree_node_get_left": {
    "args": [
      "u32"
    ],
    "returns": "i32"
  },
  "persistent_merkle_tree_node_get_right": {
    "args": [
      "u32"
    ],
    "returns": "i32"
  },
  "persistent_merkle_tree_node_get_hash": {
    "args": [
      "u32"
    ],
    "returns": "ptr"
  },
  "persistent_merkle_tree_node_get_state": {
    "args": [
      "u32"
    ],
    "returns": "u32"
  },
  "persistent_merkle_tree_node_get_node": {
    "args": [
      "u32",
      "u64"
    ],
    "returns": "i32"
  },
  "persistent_merkle_tree_node_get_node_at_depth": {
    "args": [
      "u32",
      "u8",
      "u32"
    ],
    "returns": "i32"
  },
  "persistent_merkle_tree_node_get_nodes_at_depth": {
    "args": [
      "u32",
      "u8",
      "u32",
      "ptr",
      "u32"
    ],
    "returns": "i32"
  },
  "persistent_merkle_tree_node_set_node": {
    "args": [
      "u32",
      "u64",
      "u32"
    ],
    "returns": "i32"
  },
  "persistent_merkle_tree_node_set_node_at_depth": {
    "args": [
      "u32",
      "u8",
      "u32",
      "u32"
    ],
    "returns": "i32"
  },
  "persistent_merkle_tree_node_set_nodes_at_depth": {
    "args": [
      "u32",
      "u8",
      "ptr",
      "ptr",
      "u32"
    ],
    "returns": "i32"
  },
  "persistent_merkle_tree_node_set_nodes": {
    "args": [
      "u32",
      "ptr",
      "ptr",
      "u32"
    ],
    "returns": "i32"
  },
  "persistent_merkle_tree_node_fill_to_depth": {
    "args": [
      "u32",
      "u8",
      "bool"
    ],
    "returns": "i32"
  },
  "persistent_merkle_tree_node_fill_to_length": {
    "args": [
      "u32",
      "u8",
      "u32",
      "bool"
    ],
    "returns": "i32"
  },
  "persistent_merkle_tree_node_fill_with_contents": {
    "args": [
      "ptr",
      "u32",
      "u8",
      "bool"
    ],
    "returns": "i32"
  }
} as const;
const lib = await openLibrary(path.join(import.meta.dirname, ".."), fns);

export const binding = lib.symbols;
export const close = lib.close;

